# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: DeployToAKS
  displayName: Deploy to AKS
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'devops-cluster-svconnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Deploying to AKS..."
          az aks get-credentials --resource-group nginx-dep-cluster-rgp --name nginx-cluster
          kubectl apply -f nginx-deployment.yaml
      displayName: 'Deploy resources to AKS'

